version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        # Ignore version upgrades.
        # Security updates are nevertheless. unaffected by this setting and will continue to work.
        update-types: ["version-update:semver-patch", "version-update:semver-minor", "version-update:semver-major"]
