name: "Issue Sync"
description: "Synchronizes issues to a project board"
author: paritytech
branding:
  icon: check-square
  color: green
inputs:
  project:
    required: true
    description: The number of the project which the issues will be synced to
    type: number
  project_field:
    required: false
    description: The name of the project field which the issue will be assigned to
    type: string
  project_value:
    required: false
    description: The value which will be set in the field
    type: string
  GITHUB_TOKEN:
    required: true
    type: string
  PROJECT_TOKEN:
    required: true
    type: string
runs:
  using: 'docker'
  image: 'Dockerfile'
