name: "Issue Sync"
description: "Synchronizes issues to a project board"
author: paritytech
branding:
  icon: check-square
  color: green
inputs:
  project:
    required: true
    type: number
  GITHUB_TOKEN:
    required: true
    type: string
  PROJECT_TOKEN:
    required: true
    type: string
runs:
  using: 'docker'
  image: 'Dockerfile'
