version: "3"
services:
  app:
    build:
      context: .
      dockerfile: src/server/Dockerfile
      args:
        - PORT
    depends_on:
      - db
    ports:
      - ${PORT:-3000}:3000
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_NAME: postgres
      DB_PASSWORD: null
      PORT: ${PORT:-3000}
    # uncomment the following for testing the development commands
    # entrypoint: sh
    # command: ["-c", "yarn migrations:build && yarn migrations:up && yarn dev"]
  db:
    image: docker.io/bitnami/postgresql:11-debian-10
    volumes:
      - db-data:/bitnami/postgresql
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"

volumes:
  db-data:
    driver: local
