name: Continuous testing

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Use node 18
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test
      - name: Run lint
        run: yarn lint
      - name: Build the project
        run: yarn build
